export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL = 'ORDER_FAIL'

export const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST'
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS'
export const MY_ORDER_FAIL = 'MY_ORDER_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERROR'