export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_RESET = "PRODUCT_DETAIL_RESET"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST"
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS"
export const SUBMIT_REVIEW_RESET = "SUBMIT_REVIEW_RESET"
export const SUBMIT_REVIEW_FAIL = "PRODUCT_DETAIL_FAIL"

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

export const CLEAR_ERRORS = "CLEAR_EARRORS"
